### ISSUE TITLE
git.daplie.com is not accessible

### ISSUE THREAD

**Issue by RohanTalip** [solderjs/node-bufferjs#15]
README.md points to https://git.daplie.com/coolaj86/node-bufferjs however git.daplie.com does not resolve to an IP address.

**Comment by coolaj86** [comment]
Reverted the README back to what it was years ago.

This module is deprecated in favor of node's native `Buffer`.

I created this back before node.js was cool - in the io.js days. Since then the node.js APIs have improved significantly.

**Comment by coolaj86** [comment]
Meaning: yes, you can use this... but you could also just use https://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength
